modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL="https://github.com/Kotori316/LimitMobSpawn/issues"
[[mods]]
modId = "limitmobspawn"
version = "${file.jarVersion}"
displayName = "Limit Mob Spawn"
credits = "Kotori316"
authors = "Kotori316"
displayURL="https://github.com/Kotori316/LimitMobSpawn"
description = '''
Prevent mobs from spawning.
'''
[[dependencies.limitmobspawn]]
modId = "forge"
mandatory = true
versionRange = "[40.1.14,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.limitmobspawn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
