# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ./gradlew
      - run: ./gradlew assemble
      - run: ./gradlew test
      - run: ./gradlew runData
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: build/reports/tests/*
          name: Test-Report-LMS
